CREATE TABLE BOOKS_AUD
(
    EVENT_ID       INT(11)  NOT NULL AUTO_INCREMENT,
    EVENT_DATE     DATETIME NOT NULL,
    EVENT_TYPE     VARCHAR(10) DEFAULT NULL,
    BOOK_ID        INT(11)  NOT NULL,
    OLD_TITLE      VARCHAR(250),
    NEW_TITLE      VARCHAR(250),
    OLD_PUBYEAR    INT(4),
    NEW_PUBYEAR    INT(4),
    OLD_BESTSELLER BOOL,
    NEW_BESTSELLER BOOL,
    PRIMARY KEY (EVENT_ID)

);

DELIMITER $$
CREATE TRIGGER BOOKS_INSERT
    AFTER INSERT
    ON books
    FOR EACH ROW
BEGIN
    INSERT INTO books_aud(EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_PUBYEAR, NEW_BESTSELLER)
        VALUE (CURTIME(), 'INSERT', NEW.BOOK_ID, NEW.TITLE, NEW.PUBYEAR, NEW.BESTSELLER);
END $$
DELIMITER ;

INSERT INTO BOOKS(TITLE, PUBYEAR, BESTSELLER)
VALUES ('The  New Stranger', 1943, 0);

DELIMITER $$
CREATE TRIGGER BOOKS_DELETE
    AFTER DELETE
    ON books
    FOR EACH ROW
BEGIN
    INSERT INTO books_aud(EVENT_DATE, EVENT_TYPE, BOOK_ID, OLD_TITLE, OLD_PUBYEAR, OLD_BESTSELLER)
        VALUE (CURTIME(), 'DELETE', OLD.BOOK_ID, OLD.TITLE, OLD.PUBYEAR, OLD.BESTSELLER);
END $$
DELIMITER ;

DELETE
FROM books
WHERE BOOK_ID = 8;

INSERT INTO BOOKS(TITLE, PUBYEAR, BESTSELLER)
VALUES ('New Book', 1111, true);

DELIMITER $$
CREATE TRIGGER BOOKS_UPDATE
    AFTER UPDATE
    ON books
    FOR EACH ROW
BEGIN
    INSERT INTO books_aud(EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, OLD_TITLE, NEW_PUBYEAR, OLD_PUBYEAR,
                          NEW_BESTSELLER, OLD_BESTSELLER)
        VALUE (CURTIME(), 'UPDATE', OLD.BOOK_ID, NEW.TITLE, OLD.TITLE, NEW.PUBYEAR, OLD.PUBYEAR, NEW.BESTSELLER,
               OLD.BESTSELLER);
END $$
DELIMITER ;

UPDATE BOOKS
SET TITLE = 'Old Book'
WHERE BOOK_ID = 9;

CREATE TABLE READERS_AUD
(
    EVENT_ID      INT(11)  NOT NULL AUTO_INCREMENT,
    EVENT_DATE    DATETIME NOT NULL,
    EVENT_TYPE    VARCHAR(10) DEFAULT NULL,
    READER_ID     INT(11),
    OLD_FIRSTNAME VARCHAR(255),
    NEW_FIRSTNAME VARCHAR(255),
    OLD_LASTNAME  VARCHAR(255),
    NEW_LASTNAME  VARCHAR(255),
    OLD_PESEL_ID  VARCHAR(255),
    NEW_PESEL_ID  VARCHAR(255),
    OLD_VIP_LEVEL VARCHAR(255),
    NEW_VIP_LEVEL VARCHAR(255),
    PRIMARY KEY (EVENT_ID)
);

DELIMITER $$
CREATE TRIGGER READERS_INSERT
    AFTER INSERT
    ON readers
    FOR EACH ROW
BEGIN
    INSERT INTO readers_aud(EVENT_DATE, EVENT_TYPE, READER_ID, NEW_FIRSTNAME, NEW_LASTNAME, NEW_PESEL_ID, NEW_VIP_LEVEL)
        VALUE (CURTIME(), 'INSERT', NEW.READER_ID, NEW.FIRSTNAME, NEW.LASTNAME, NEW.PESEL_ID, NEW_VIP_LEVEL);
END $$
DELIMITER ;

INSERT INTO READERS(FIRSTNAME, LASTNAME, PESEL_ID, VIP_LEVEL)
VALUES ('John', 'Doe', '0000000001', 'Standard customer');

INSERT INTO READERS(FIRSTNAME, LASTNAME, PESEL_ID, VIP_LEVEL)
VALUES ('Jane', 'Doe', '111111111', 'Standard customer');


DELIMITER $$
CREATE TRIGGER READERS_DELETE
    AFTER DELETE
    ON readers
    FOR EACH ROW
BEGIN
    INSERT INTO readers_aud(EVENT_DATE, EVENT_TYPE, READER_ID, OLD_FIRSTNAME, OLD_LASTNAME, OLD_PESEL_ID, OLD_VIP_LEVEL)
        VALUE (CURTIME(), 'DELETE', OLD.READER_ID, OLD.FIRSTNAME, OLD.LASTNAME, OLD.PESEL_ID, OLD.VIP_LEVEL);
END $$
DELIMITER ;

DELETE
FROM readers
WHERE READER_ID = 6;

DELIMITER $$
CREATE TRIGGER READERS_UPDATE
    AFTER UPDATE
    ON readers
    FOR EACH ROW
BEGIN
    INSERT INTO readers_aud(EVENT_DATE, EVENT_TYPE, READER_ID, NEW_FIRSTNAME, OLD_FIRSTNAME, NEW_LASTNAME, OLD_LASTNAME,
                            NEW_PESEL_ID, OLD_PESEL_ID, NEW_VIP_LEVEL, OLD_VIP_LEVEL)
        VALUE (CURTIME(), 'UPDATE', OLD.READER_ID, NEW.FIRSTNAME, OLD.FIRSTNAME, NEW.LASTNAME, OLD.LASTNAME,
               NEW.PESEL_ID,
               OLD.PESEL_ID, NEW.VIP_LEVEL, OLD_VIP_LEVEL);
END $$
DELIMITER ;

UPDATE readers
SET FIRSTNAME = 'Jan',
    LASTNAME  = 'Kovalsky',
    PESEL_ID  =05222400658,
    VIP_LEVEL = 'Gold Customer'
WHERE READER_ID = 7;




